Repository UMC5th-DrinkingGourmet/dg-FrontEnd, pull requests merged in 2024-08, with the labels that each got.

#147 [#146] 메인페이지 UI 컴포넌트 레이아웃 보완
  DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
Labels: :wrench: Fix

#151 [#145] feat: 내 정보 수정 API 연결
  DrinkingGourmet/Source/Mypage/ViewController/MyPageViewController.swift
  DrinkingGourmet/Source/Service/MyPageService.swift
  DrinkingGourmet/Source/Setting/Home/View/SettingTopView.swift
  DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
  DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
Labels: :sparkles: Feature

#163 [#144] feat: 오늘의 조합 게시글 수정 및 회원탈퇴 API 연결
  DrinkingGourmet/Source/Combination/Detail/ViewController/CombinationDetailViewController.swift
  DrinkingGourmet/Source/Combination/Upload/ViewController/CombinationUploadVC.swift
  DrinkingGourmet/Source/Network/Service/CombinationService.swift
  DrinkingGourmet/Source/Network/Service/SignService.swift
  DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailViewController.swift
  DrinkingGourmet/Source/RecipeBook/Upload/ViewController/RecipeBookUploadViewController.swift
  DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
  DrinkingGourmet/Source/UserAuthentication/Viewcontroller/AuthenticationViewController.swift
Labels: :sparkles: Feature

#165 [#164] feat: 레시피북 게시글 수정 API 연결
  DrinkingGourmet/Source/Network/Service/RecipeBookService.swift
  DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailViewController.swift
  DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeViewController.swift
  DrinkingGourmet/Source/RecipeBook/Upload/ViewController/RecipeBookUploadViewController.swift
Labels: :recycle: Refactor, :sparkles: Feature

#168 [#167] refacotr: 약관동의 UI 리펙토링
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_terms_total_checked.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_terms_total_checked.imageset/ic_total_terms_checked.png
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_terms_total_unchecked.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_terms_total_unchecked.imageset/ic_total_terms_unchecked.png
  DrinkingGourmet/Source/Network/Service/AdministrationService.swift
  DrinkingGourmet/Source/UserAuthentication/Viewcontroller/TermsViewController.swift
Labels: :recycle: Refactor, :art: Design

#170 [#169] feat: 이용약관 API 연결
  DrinkingGourmet/Source/UserAuthentication/Viewcontroller/TermsViewController.swift
Labels: :sparkles: Feature
