Repository UMC5th-DrinkingGourmet/dg-FrontEnd, pull requests merged in 2024-07, with the labels that each got.

#122 [#92] Feat: 자주 묻는 질문 UI 구현
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/App/SceneDelegate.swift
  DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
  DrinkingGourmet/Source/Setting/Question/View/AnswerView.swift
  DrinkingGourmet/Source/Setting/Question/View/DeleteAccountView.swift
  DrinkingGourmet/Source/Setting/Question/View/QuestionCell.swift
  DrinkingGourmet/Source/Setting/Question/View/QuestionView.swift
  DrinkingGourmet/Source/Setting/Question/ViewController/AnswerViewController.swift
  DrinkingGourmet/Source/Setting/Question/ViewController/DeleteAccountViewController.swift
  DrinkingGourmet/Source/Setting/Question/ViewController/QuestionViewController.swift
Labels: :sparkles: Feature

#124 [#123] Feat: 게시물 커스텀 팝업뷰 구현
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_aleart.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_aleart.imageset/ic_aleart.png
  DrinkingGourmet/Source/Combination/Detail/ViewController/CombinationDetailViewController.swift
  DrinkingGourmet/Source/Combination/RemovedAlertView.swift
  DrinkingGourmet/Source/Combination/RemovedAlertViewController.swift
  DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailViewController.swift
Labels: :sparkles: Feature

#129 [#128] Refactor: 좋아요 페이지 리펙토링
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DrinkingGourmet/Source/Like/View/LikeView.swift
  DrinkingGourmet/Source/Like/ViewController/LikeCombinationViewController.swift
  DrinkingGourmet/Source/Like/ViewController/LikeRecipeBookViewController.swift
  DrinkingGourmet/Source/Like/ViewController/LikeTapmanViewController.swift
  DrinkingGourmet/Source/Report/ViewController/ReportViewController.swift
  DrinkingGourmet/Source/TabBar/Viewcontroller/TabBarViewController.swift
Labels: :recycle: Refactor

#132 [#131] Feat: 마이페이지 약관 및 정책 구현
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
  DrinkingGourmet/Source/Setting/Question/ViewController/AnswerViewController.swift
  DrinkingGourmet/Source/Setting/TermsAndPolicies/TermsAndPoliciesViewController.swift
Labels: :sparkles: Feature

#134 [#133] Design: 마이페이지 Cell 디자인 수정
  DrinkingGourmet/Source/Setting/Home/View/SettingCell.swift
  DrinkingGourmet/Source/Setting/Home/ViewController/SettingViewController.swift
Labels: :art: Design, :sparkles: Feature

#138 [#137] Feat: 차단 구현
  DrinkingGourmet/Source/Combination/Detail/ViewController/CombinationDetailViewController.swift
  DrinkingGourmet/Source/Like/ViewController/LikeCombinationViewController.swift
  DrinkingGourmet/Source/Like/ViewController/LikeRecipeBookViewController.swift
  DrinkingGourmet/Source/Like/ViewController/LikeTapmanViewController.swift
  DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailViewController.swift
  DrinkingGourmet/Source/Report/View/ReportCompletePopUpView.swift
Labels: :sparkles: Feature

#141 네트워킹 리팩토링 및 토큰 갱신 로직 구현
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/App/SceneDelegate.swift
  DrinkingGourmet/Source/Combination/Upload/ViewController/CombinationUploadVC.swift
  DrinkingGourmet/Source/RecipeBook/Upload/ViewController/RecipeBookUploadViewController.swift
  DrinkingGourmet/Source/Service/AdministrationService.swift
  DrinkingGourmet/Source/Service/Auth/AuthInterceptor.swift
  DrinkingGourmet/Source/Service/CombinationService.swift
  DrinkingGourmet/Source/Service/CombinationUpoadService.swift
  DrinkingGourmet/Source/Service/Dto/CombinationUploadInput.swift
  DrinkingGourmet/Source/Service/Dto/CombinationUploadModel.swift
  DrinkingGourmet/Source/Service/Dto/RecipeBookUploadDTO.swift
  DrinkingGourmet/Source/Service/Dto/SignInInfoDTO.swift
  DrinkingGourmet/Source/Service/Dto/UserInfoDTO.swift
  DrinkingGourmet/Source/Service/LikeService.swift
  DrinkingGourmet/Source/Service/RecipeBookService.swift
  DrinkingGourmet/Source/Service/RecipeBookUploadService.swift
  DrinkingGourmet/Source/Service/SignUpService.swift
  DrinkingGourmet/Source/UserAuthentication/Model/UserInfoDataManager.swift
  DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
Labels: :sparkles: Feature
