Repository UMC5th-DrinkingGourmet/dg-FrontEnd, pull requests merged in 2024-06, with the labels that each got.

#110 [#109] Refactor: 오늘의 조합 네트워킹 리펙토링
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DrinkingGourmet/Source/Community/Home/ViewController/CommunityViewController.swift
  DrinkingGourmet/Source/Like/ViewController/LikeViewController.swift
  DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
  DrinkingGourmet/Source/Mypage/ViewController/MyPageViewController.swift
  DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailVC.swift
  DrinkingGourmet/Source/Report/ViewController/ReportViewController.swift
  DrinkingGourmet/Source/Service/CombinationService.swift
  DrinkingGourmet/Source/Service/Dto/CombinationDto.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationCommentInput.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationCommentModel.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailModel.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/CombinationDetailCommentCell.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/CombinationDetailHeaderView.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentInputView.swift
  DrinkingGourmet/Source/TodayCombination/Detail/ViewController/CombinationDetailViewController.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeInput.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeModel.swift
  DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationCell.swift
  DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationView.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/CombiationViewController.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/CombinationSearchVC.swift
  DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestVC.swift
Labels: :recycle: Refactor

#116 [#115] Refactor: 좋아요 리펙토링 및 리프레쉬 구현
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/Like/Model/LikeAllCombinationModel.swift
  DrinkingGourmet/Source/Like/Model/LikeAllRecipeBookModel.swift
  DrinkingGourmet/Source/Like/Model/LikeDataManager.swift
  DrinkingGourmet/Source/Like/Model/LikeInput.swift
  DrinkingGourmet/Source/Like/View/LikeCell.swift
  DrinkingGourmet/Source/Like/View/LikeView.swift
  DrinkingGourmet/Source/Like/ViewController/LikeViewController.swift
  DrinkingGourmet/Source/Service/Dto/LikeDTO.swift
  DrinkingGourmet/Source/Service/LikeService.swift
Labels: :recycle: Refactor, :sparkles: Feature

#118 [#117] Feat: 토스트뷰 구현 및 리펙토링
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DrinkingGourmet/Source/Like/ViewController/LikeViewController.swift
  DrinkingGourmet/Source/Report/View/ReportCompletePopUpView.swift
  DrinkingGourmet/Source/Report/View/ReportView.swift
  DrinkingGourmet/Source/Report/ViewController/ReportViewController.swift
Labels: :recycle: Refactor, :sparkles: Feature

#121 [#120] 애플 소셜 로그인 구현
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/App/SceneDelegate.swift
  DrinkingGourmet/Info.plist
  DrinkingGourmet/Source/UserAuthentication/AppleAuthViewModel.swift
  DrinkingGourmet/Source/UserAuthentication/Model/UserInfoDataManager.swift
  DrinkingGourmet/Source/UserAuthentication/Viewcontroller/AuthenticationViewController.swift
  DrinkingGourmet/Source/UserAuthentication/Viewcontroller/ProfileCreationViewController.swift
Labels: :sparkles: Feature
