Repository UMC5th-DrinkingGourmet/dg-FrontEnd, pull requests merged in 2024-02, with the labels that each got.

#18 Feat: 오늘의 조합 상세보기 UI 최종 구현
  DrinkingGourmet/Source/TodayCombination/Detail/View/TodayCombinationDetailView.swift
  DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
Labels: feature💦

#20 feat: 사진 업로드 구현
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/.gitignore
  DrinkingGourmet/App/AppDelegate.swift
  DrinkingGourmet/App/SceneDelegate.swift
  DrinkingGourmet/Info.plist
  DrinkingGourmet/Resource/Assets.xcassets/Colors/CheckmarkGray.colorset/Contents.json
  DrinkingGourmet/Source/Authentication/KakaoAuthViewModel.swift
  DrinkingGourmet/Source/Authentication/Viewcontroller/AuthenticationViewController.swift
  DrinkingGourmet/Source/Authentication/Viewcontroller/TermsViewController.swift
  DrinkingGourmet/Source/Upload/UploadedImgCollectionViewCell.swift
  DrinkingGourmet/Source/Upload/ViewController/UploadViewController.swift
  DrinkingGourmet/Util/Extension/UIColor+CustomColor.swift
Labels: feature💦

#21 Feat: 오늘의 조합 홈 플로팅버튼 구현
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_floating_show.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_floating_show.imageset/ic_floating_show.png
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_modify.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_modify.imageset/ic_modify.png
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_write.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_write.imageset/ic_write.png
  DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationView.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
Labels: feature💦

#24 Feat: 검색창 구현 및 커뮤니티 홈 UI구현
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_community_home_combination.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_community_home_combination.imageset/img_community_home_combination.png
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_community_home_recipebook.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_community_home_recipebook.imageset/img_community_home_recipebook.png
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_community_home_weeklybest.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_community_home_weeklybest.imageset/img_community_home_weeklybest.png
  DrinkingGourmet/Source/Community/Home/Model/CommunityHome.swift
  DrinkingGourmet/Source/Community/Home/Model/CommunityHomeDataManager.swift
  DrinkingGourmet/Source/Community/Home/View/CommunityHomeCell.swift
  DrinkingGourmet/Source/Community/Home/View/CommunityHomeView.swift
  DrinkingGourmet/Source/Community/Home/ViewController/CommunityHomeVC.swift
  DrinkingGourmet/Source/Community/Search/View/CustomResultSearchBar.swift
  DrinkingGourmet/Source/Community/Search/View/CustomSearchBar.swift
  DrinkingGourmet/Source/Community/Search/View/SearchResultCell.swift
  DrinkingGourmet/Source/Community/Search/View/SearchResultView.swift
  DrinkingGourmet/Source/Community/Search/ViewController/SearchResultVC.swift
Labels: feature💦

#25 Feat: 주간 베스트 조합 UI 구현 및 오늘의 조합 홈 화면 수정
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/Community/Home/ViewController/CommunityHomeVC.swift
  DrinkingGourmet/Source/Community/Home/ViewController/WeeklyBestCell.swift
  DrinkingGourmet/Source/Community/Home/ViewController/WeeklyBestView.swift
  DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationView.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
  DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestVC.swift
  DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestViewController.swift
Labels: feature💦

#26 Feat: 음주미식회 레시피북 UI 구현
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/Community/Home/ViewController/CommunityHomeVC.swift
  DrinkingGourmet/Source/RecipeBook/Detail/View/RecipeBookDetailCell.swift
  DrinkingGourmet/Source/RecipeBook/Detail/View/RecipeBookDetailInfoView.swift
  DrinkingGourmet/Source/RecipeBook/Detail/View/RecipeBookDetailView.swift
  DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailVC.swift
  DrinkingGourmet/Source/RecipeBook/Home/View/RecipeBookHomeCell.swift
  DrinkingGourmet/Source/RecipeBook/Home/View/RecipeBookHomeView.swift
  DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeVC.swift
Labels: feature💦

#34 Feat: 오늘의조합 홈 API 연동
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeInput.swift
  DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeModel.swift
  DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationCell.swift
  DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationView.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
Labels: feature💦

#35 Feat: 오늘의조합 검색 API 연동
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeInput.swift
  DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeModel.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/CombinationSearchVC.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
Labels: feature💦

#38 Feat: 레시피북 홈 & 상세보기 GET API 연동 (댓글 전)
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/RecipeBook/Detail/Model/RecipeBookDetailDataManager.swift
  DrinkingGourmet/Source/RecipeBook/Detail/Model/RecipeBookDetailImageInput.swift
  DrinkingGourmet/Source/RecipeBook/Detail/Model/RecipeBookDetailImageModel.swift
  DrinkingGourmet/Source/RecipeBook/Detail/Model/RecipeBookDetailModel.swift
  DrinkingGourmet/Source/RecipeBook/Detail/View/RecipeBookDetailInfoView.swift
  DrinkingGourmet/Source/RecipeBook/Detail/View/RecipeBookDetailView.swift
  DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailVC.swift
  DrinkingGourmet/Source/RecipeBook/Home/Model/RecipeBookHomeDataManager.swift
  DrinkingGourmet/Source/RecipeBook/Home/Model/RecipeBookHomeInput.swift
  DrinkingGourmet/Source/RecipeBook/Home/Model/RecipeBookHomeModel.swift
  DrinkingGourmet/Source/RecipeBook/Home/View/RecipeBookHomeCell.swift
  DrinkingGourmet/Source/RecipeBook/Home/View/RecipeBookHomeView.swift
  DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeVC.swift
  DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookSearchVC.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationCommentInput.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationCommentModel.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailModel.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentAreaView.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentsView.swift
  DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
  DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeInput.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeModel.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
Labels: feature💦

#37 Feat: 오늘의 조합 홈 리팩토링 & 상세보기 GET API 연동
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationCommentInput.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationCommentModel.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailModel.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentAreaView.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentsView.swift
  DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
  DrinkingGourmet/Source/TodayCombination/Home/CombinationHomeDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeInput.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeModel.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
Labels: feature💦

#39 Feat: 주간 베스트 조합 API 연동
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/Community/Home/ViewController/WeeklyBestCell.swift
  DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestDataManager.swift
  DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestInput.swift
  DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestModel.swift
  DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestSearchVC.swift
  DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestVC.swift
Labels: feature💦

#40 Revert "Feat: 주간 베스트 조합 API 연동"
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/Community/Home/ViewController/WeeklyBestCell.swift
  DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestDataManager.swift
  DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestInput.swift
  DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestModel.swift
  DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestSearchVC.swift
  DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestVC.swift
Labels: bug🐞

#41 Feat: 주간 베스트 조합 API 연동
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/Community/Home/ViewController/WeeklyBestCell.swift
  DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestDataManager.swift
  DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestInput.swift
  DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestModel.swift
  DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestSearchVC.swift
  DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestVC.swift
Labels: Fix🛠️

#42 Feat: 오늘의 조합 댓글 구현 (대댓글 구현 전)
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationCommentInput.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationCommentModel.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailModel.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentsView.swift
  DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeInput.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeModel.swift
  DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationCell.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/CombinationSearchVC.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
Labels: ♻️Refactor, feature💦

#44 Feat: 좋아요 뷰 좋아요 한 오늘의 조합 조회 API 연동
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DrinkingGourmet/Source/Like/Model/LikeAllCombinationModel.swift
  DrinkingGourmet/Source/Like/Model/LikeAllRecipeBookModel.swift
  DrinkingGourmet/Source/Like/Model/LikeDataManager.swift
  DrinkingGourmet/Source/Like/Model/LikeInput.swift
  DrinkingGourmet/Source/Like/View/LikeCell.swift
  DrinkingGourmet/Source/Like/View/LikeView.swift
  DrinkingGourmet/Source/Like/ViewController/LikeViewController.swift
Labels: feature💦

#47 Feat: 오늘의 조합 업로드 UI
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/App/SceneDelegate.swift
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_upload_more_false.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_upload_more_false.imageset/ic_upload_more_false.png
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_upload_more_true.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_upload_more_true.imageset/ic_upload_more_true.png
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
  DrinkingGourmet/Source/TodayCombination/Upload/Model/CombinationUploadDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Upload/Model/CombinationUploadInput.swift
  DrinkingGourmet/Source/TodayCombination/Upload/Model/CombinationUploadModel.swift
  DrinkingGourmet/Source/TodayCombination/Upload/ViewController/CombinationUploadVC.swift
Labels: feature💦

#51 Refactor: 오늘의 조합 홈 페이징 처리 리펙토링
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
Labels: ♻️Refactor

#52 Refactor: 오늘의 조합 API 수정 후 모델 수정 및 리펙토링
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationCommentModel.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailModel.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentsView.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/TodayCombinationDetailView.swift
  DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
Labels: ♻️Refactor

#53 Feat: 댓글 UI 수정 및 오늘의 조합 좋아요 관련 UI 수정, API 연동
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentView.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentsView.swift
  DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeModel.swift
  DrinkingGourmet/Source/TodayCombination/Home/View/TodayCombinationCell.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
Labels: ♻️Refactor, feature💦

#54 Feat: 오늘의 조합 게시글 삭제 API 연동
  DrinkingGourmet/Source/TodayCombination/Detail/Model/CombinationDetailDataManager.swift
  DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
Labels: feature💦

#55 Refactor: 레시피북 홈 조회 모델수정 및 페이징 버그 수정
  DrinkingGourmet/Source/RecipeBook/Home/Model/RecipeBookHomeModel.swift
  DrinkingGourmet/Source/RecipeBook/Home/View/RecipeBookHomeCell.swift
  DrinkingGourmet/Source/RecipeBook/Home/ViewController/RecipeBookHomeVC.swift
Labels: bug🐞, ♻️Refactor, feature💦

#56 Refactor: 레시피북 상세정보 API 연동
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/RecipeBook/Detail/Model/RecipeBookCommentInput.swift
  DrinkingGourmet/Source/RecipeBook/Detail/Model/RecipeBookCommentModel.swift
  DrinkingGourmet/Source/RecipeBook/Detail/Model/RecipeBookDetailDataManager.swift
  DrinkingGourmet/Source/RecipeBook/Detail/Model/RecipeBookDetailImageInput.swift
  DrinkingGourmet/Source/RecipeBook/Detail/Model/RecipeBookDetailImageModel.swift
  DrinkingGourmet/Source/RecipeBook/Detail/Model/RecipeBookDetailModel.swift
  DrinkingGourmet/Source/RecipeBook/Detail/View/RecipeBookDetailView.swift
  DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailVC.swift
  DrinkingGourmet/Source/RecipeBook/Home/Model/RecipeBookHomeModel.swift
  DrinkingGourmet/Source/TodayCombination/Detail/View/Comments/CommentsView.swift
Labels: ♻️Refactor, feature💦

#57 Feat: 좋아요 페이지 구현
  DrinkingGourmet/Source/Like/Model/LikeAllRecipeBookModel.swift
  DrinkingGourmet/Source/Like/Model/LikeDataManager.swift
  DrinkingGourmet/Source/Like/ViewController/LikeViewController.swift
Labels: feature💦

#58 Feat: 마이페이지 UI 구현
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_profile_mypage.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/ic_profile_mypage.imageset/Image.png
  DrinkingGourmet/Source/Mypage/View/MyPageCell.swift
  DrinkingGourmet/Source/Mypage/View/MyPageLowerView.swift
  DrinkingGourmet/Source/Mypage/View/MyPageView.swift
  DrinkingGourmet/Source/Mypage/ViewController/MyPageViewController.swift
Labels: feature💦

#59 Feat: 마이페이지 API연동 페이징 전
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/Mypage/Model/MyPageCombinationModel.swift
  DrinkingGourmet/Source/Mypage/Model/MyPageDataManager.swift
  DrinkingGourmet/Source/Mypage/Model/MyPageInput.swift
  DrinkingGourmet/Source/Mypage/Model/MyPageRecipeBookModel.swift
  DrinkingGourmet/Source/Mypage/Model/MyPageRecommendModel.swift
  DrinkingGourmet/Source/Mypage/Model/MyPageUserModel.swift
  DrinkingGourmet/Source/Mypage/View/MyPageLowerView.swift
  DrinkingGourmet/Source/Mypage/View/MyPageView.swift
  DrinkingGourmet/Source/Mypage/ViewController/MyPageViewController.swift
Labels: feature💦

#60 Feat : 주류추천 API 연동(post), 주류정보입력 API 연동(Patch)
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Controller/GetUserInfoViewController.swift
  DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Controller/SelectAlcoholDegreeViewController.swift
  DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Controller/SelectDrinkCapacityViewController.swift
  DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Controller/SelectDrinkFrequencyViewController.swift
  DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Controller/SelectTypeOfLiquorViewController.swift
  DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Controller/WelcomeViewController.swift
  DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Model/MyDrinkingStyleDataManager.swift
  DrinkingGourmet/Source/Recommend/MyDrinkingStyle/Model/MyDrinkingStyleDataModels.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/Model/MyRecommendDataManager.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/Model/MyRecommendInput.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/Model/MyRecommendModelData.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/Model/SelectMyMoodResource.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/Model/SelectWeatherResource.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/GetDrinkingRecommendViewController.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/InputMyFoodViewController.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/InputMyMoodViewController.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/LoadingRecommendDrinkViewController.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/MyDrinkStyleViewController.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/RecommendViewController.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/SelectDrunkDegreeViewController.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/SelectMyMoodViewController.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/SelectWeatherViewController.swift
  DrinkingGourmet/Source/Recommend/Utils/CustomizedSlider.swift
Labels: bug🐞, ♻️Refactor, feature💦

#69 Fix: 레시피북, 조합 찐최종
  DrinkingGourmet/Source/RecipeBook/Detail/ViewController/RecipeBookDetailVC.swift
  DrinkingGourmet/Source/TodayCombination/Detail/ViewController/TodayCombinationDetailViewController.swift
Labels: Fix🛠️

#72 Fix: 주간베스트 코드 수정
  DrinkingGourmet/Source/Community/Home/ViewController/WeeklyBestCell.swift
  DrinkingGourmet/Source/WeeklyBest/Model/WeeklyBestDataManager.swift
  DrinkingGourmet/Source/WeeklyBest/ViewController/WeeklyBestVC.swift
Labels: Fix🛠️

#73 Fix: 오늘의 조합 홈화면 이미지 nil값 방지
  DrinkingGourmet/Source/TodayCombination/Home/Model/CombinationHomeModel.swift
  DrinkingGourmet/Source/TodayCombination/Home/ViewController/TodayCombinationViewController.swift
Labels: Fix🛠️

#75 Feat: 탭바 설정
  DrinkingGourmet/App/SceneDelegate.swift
  DrinkingGourmet/Source/Like/Model/LikeAllCombinationModel.swift
  DrinkingGourmet/Source/Like/Model/LikeAllRecipeBookModel.swift
  DrinkingGourmet/Source/Like/ViewController/LikeViewController.swift
  DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
  DrinkingGourmet/Source/Mypage/ViewController/MyPageViewController.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/GetDrinkingRecommendViewController.swift
  DrinkingGourmet/Source/Recommend/MyRecommend/ViewController/MyDrinkStyleViewController.swift
  DrinkingGourmet/Source/TabBar/Viewcontroller/TabBarViewController.swift
Labels: feature💦

#76 Feat: 메인페이지 추가 작업
  DrinkingGourmet.xcodeproj/project.pbxproj
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_main_ad.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_main_ad.imageset/img_main_ad.png
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_main_new_alcohol.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_main_new_alcohol.imageset/img_main_new_alcohol.png
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_main_new_alcohol.imageset/img_main_new_alcohol@2x.png
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_main_new_alcohol.imageset/img_main_new_alcohol@3x.png
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_new_alcohol_main.imageset/Contents.json
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_new_alcohol_main.imageset/img_new_alcohol_main.png
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_new_alcohol_main.imageset/img_new_alcohol_main@2x.png
  DrinkingGourmet/Resource/Assets.xcassets/Images/img_new_alcohol_main.imageset/img_new_alcohol_main@3x.png
  DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
  DrinkingGourmet/Source/NewAlcohol/ViewController/NewAlcoholViewController.swift
Labels: feature💦

#79 Feat: 탭바 찐찐최종
  DrinkingGourmet/Source/MainMenu/ViewController/MainMenuViewController.swift
Labels: feature💦
